version: "3.3"
services:
  account_db:
    container_name: auth_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=masha
      - POSTGRES_DB=auth_db
    ports:
      - "5430:5432"
  restaurant_db:
    container_name: restaurant_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=masha
      - POSTGRES_DB=restaurant_db
    ports:
      - "5434:5432"