version: "3.3"
services:
  account_db:
    container_name: auth_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=masha
      - POSTGRES_DB=auth_db
    ports:
      - "5430:5432"

  order_db:
    container_name: order_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=masha
      - POSTGRES_DB=order_db
    ports:
      - "5431:5432"

  kitchen_db:
    container_name: kitchen_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=masha
      - POSTGRES_DB=kitchen_db
    ports:
      - "5433:5432"

  restaurant_db:
    container_name: restaurant_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=masha
      - POSTGRES_DB=restaurant_db
    ports:
      - "5434:5432"

  bonus_db:
    container_name: bonus_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=masha
      - POSTGRES_DB=bonus_db
    ports:
      - "5435:5432"
