spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5430/auth_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:masha}
  liquibase:
    change-log: classpath:db.changelog/changelog.xml
    enabled: true
jwt:
  jwt-secret: ${JWT_SECRET:secret}
  jwt-expiration-days: 0
client-settings:
  bonus-service-url: "localhost:8090"