spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5433/kitchen_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:masha}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/changelog.xml

server:
  port: 8083

client-settings:
  auth-service-url: "localhost:8080"
  order-service-url: "localhost:8081"
